// SPDX-License-Identifier: Apache-2.0
#include "pv/guard/policy_pack.hpp"

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <optional>
#include <set>
#include <string>
#include <string_view>
#include <vector>

#include <fmt/format.h>

namespace pv {
namespace {

std::string lower(std::string value) {
    std::ranges::transform(value, value.begin(), [](unsigned char ch) {
        return static_cast<char>(std::tolower(ch));
    });
    return value;
}

bool contains(std::string_view value, std::string_view needle) {
    return value.find(needle) != std::string_view::npos;
}

std::string extension_of(std::string_view path) {
    return lower(std::filesystem::path{std::string{path}}.extension().string());
}

std::string stem_of(std::string_view path) {
    return lower(std::filesystem::path{std::string{path}}.stem().string());
}

std::string filename_of(std::string_view path) {
    return lower(std::filesystem::path{std::string{path}}.filename().string());
}

bool is_source_file(std::string_view path) {
    const auto ext = extension_of(path);
    return ext == ".c" || ext == ".cc" || ext == ".cpp" || ext == ".cxx"
        || ext == ".h" || ext == ".hh" || ext == ".hpp" || ext == ".hxx"
        || ext == ".m" || ext == ".mm" || ext == ".rs" || ext == ".go"
        || ext == ".java" || ext == ".kt" || ext == ".cs" || ext == ".py"
        || ext == ".rb" || ext == ".php" || ext == ".js" || ext == ".jsx"
        || ext == ".ts" || ext == ".tsx";
}

bool is_test_file(std::string_view path) {
    const auto text = lower(std::string{path});
    const auto name = filename_of(path);
    return contains(text, "/test/") || contains(text, "/tests/")
        || contains(text, "test_") || contains(text, "_test")
        || contains(text, ".test.") || contains(text, "spec_")
        || contains(text, "_spec") || contains(text, ".spec.")
        || contains(name, "test") || contains(name, "spec");
}

bool is_lockfile(std::string_view path) {
    const auto name = filename_of(path);
    return name == "package-lock.json" || name == "yarn.lock" || name == "pnpm-lock.yaml"
        || name == "cargo.lock" || name == "go.sum" || name == "poetry.lock"
        || name == "pipfile.lock" || name == "gemfile.lock" || name == "composer.lock";
}

bool is_policy_approval(std::string_view path) {
    const auto text = lower(std::string{path});
    return contains(text, "policy") || contains(text, "approval")
        || contains(text, ".github/dependabot") || contains(text, "security-review");
}

bool is_workflow(std::string_view path) {
    const auto text = lower(std::string{path});
    const auto name = filename_of(path);
    return contains(text, ".github/workflows/")
        || name == ".gitlab-ci.yml"
        || name == ".gitlab-ci.yaml"
        || name == "azure-pipelines.yml"
        || name == "azure-pipelines.yaml"
        || name == "circle.yml";
}

bool is_generated_path(std::string_view path) {
    const auto text = lower(std::string{path});
    return contains(text, "/generated/")
        || contains(text, "/gen/")
        || contains(text, "/dist/")
        || contains(text, "/build/")
        || contains(text, "/vendor/")
        || contains(text, ".generated.");
}

bool has_generated_marker(const GitDiffEntry& entry) {
    for (const auto& line : entry.added_lines) {
        const auto text = lower(line.text);
        if (contains(text, "@generated") || contains(text, "generated by") || contains(text, "do not edit")) {
            return true;
        }
    }
    return false;
}

bool status_changes_file(GitDiffStatus status) {
    return status == GitDiffStatus::Modified || status == GitDiffStatus::Added
        || status == GitDiffStatus::Renamed || status == GitDiffStatus::Copied
        || status == GitDiffStatus::TypeChanged;
}

bool matching_test_changed(std::string_view source, const std::vector<GitDiffEntry>& entries) {
    auto stem = stem_of(source);
    if (stem.empty()) {
        return false;
    }
    for (const auto& entry : entries) {
        if (!status_changes_file(entry.status) || !is_test_file(entry.path)) {
            continue;
        }
        const auto test_path = lower(entry.path);
        if (contains(test_path, stem)) {
            return true;
        }
    }
    return false;
}

bool secret_pattern(std::string_view file, std::string_view text) {
    const auto path = lower(std::string{file});
    const auto line = lower(std::string{text});
    return contains(line, "aws_access_key_id")
        || contains(line, "secret_key=")
        || contains(line, "secret=")
        || contains(line, "private key")
        || contains(line, "token=")
        || contains(line, "api_key=")
        || contains(line, "apikey=")
        || (contains(path, ".env") && contains(line, "="));
}

GuardFinding finding(FindingSeverity severity, std::string rule, std::string message, std::string file = {}, std::optional<int> line = std::nullopt) {
    GuardFinding out;
    out.severity = severity;
    out.rule = std::move(rule);
    out.message = std::move(message);
    out.file = std::move(file);
    out.line = line;
    return out;
}

}  // namespace

std::vector<GuardFinding> PrGuardPolicyPack::evaluate(const std::vector<GitDiffEntry>& entries) const {
    std::vector<GuardFinding> findings;
    int total_additions = 0;
    int total_deletions = 0;
    bool policy_approval_changed = false;
    std::set<std::string> generated_reported;

    for (const auto& entry : entries) {
        total_additions += entry.additions;
        total_deletions += entry.deletions;
        policy_approval_changed = policy_approval_changed || is_policy_approval(entry.path);
    }

    for (const auto& entry : entries) {
        if (status_changes_file(entry.status)
            && is_source_file(entry.path)
            && !is_test_file(entry.path)
            && !is_generated_path(entry.path)
            && !matching_test_changed(entry.path, entries)) {
            findings.push_back(finding(
                FindingSeverity::High,
                "modified_source_requires_test",
                fmt::format("{} modified but no matching test file changed", entry.path),
                entry.path));
        }

        if (entry.status == GitDiffStatus::Deleted && is_test_file(entry.path)) {
            findings.push_back(finding(
                FindingSeverity::High,
                "deleted_test_is_high_risk",
                fmt::format("{} deleted from test coverage", entry.path),
                entry.path));
        }

        if (is_workflow(entry.path)) {
            findings.push_back(finding(
                FindingSeverity::High,
                "workflow_change_is_high_risk",
                fmt::format("{} changes CI or deployment workflow state", entry.path),
                entry.path));
        }

        if (is_lockfile(entry.path) && !policy_approval_changed) {
            findings.push_back(finding(
                FindingSeverity::Medium,
                "lockfile_change_requires_policy",
                fmt::format("{} changed without policy approval", entry.path),
                entry.path));
        }

        if (is_generated_path(entry.path) || has_generated_marker(entry)) {
            if (generated_reported.insert(entry.path).second) {
                findings.push_back(finding(
                    FindingSeverity::Medium,
                    "generated_file_change_is_medium_risk",
                    fmt::format("{} appears to be generated or vendored output", entry.path),
                    entry.path));
            }
        }

        for (const auto& line : entry.added_lines) {
            if (secret_pattern(line.file, line.text)) {
                findings.push_back(finding(
                    FindingSeverity::Critical,
                    "secret_pattern_in_diff_is_critical",
                    fmt::format("possible secret introduced in {}", line.file),
                    line.file,
                    line.line));
            }
        }
    }

    if (entries.size() >= 20 || total_additions + total_deletions >= 500) {
        findings.push_back(finding(
            FindingSeverity::Medium,
            "large_diff_is_medium_risk",
            fmt::format("{} changed files and {} changed lines", entries.size(), total_additions + total_deletions)));
    }

    findings.push_back(finding(
        FindingSeverity::Info,
        "changed_files_mapped_into_audit_graph",
        fmt::format("{} changed files mapped into audit graph", entries.size())));

    return findings;
}

}  // namespace pv
